name: Build and test the project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rust:1.97.1
    strategy:
      matrix:
        BUILD_TARGET: [release] # refers to a cargo profile
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install components
        run: rustup component add rustfmt clippy

      - name: Cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy (linting)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: rust_training_project-${{ matrix.BUILD_TARGET }}
          path: target/${{ matrix.BUILD_TARGET }}/rust_training_project

      - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo test --profile ${{ matrix.BUILD_TARGET }}

      - name: Build documentation
        run: cargo doc --no-deps --profile ${{ matrix.BUILD_TARGET }}
